#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to load-balancer

display_funct() {
	 dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]; then
	display_funct "$2.$1" "$2"
else
	display_funct "www.$1" "www"
	display_funct "lb-01.$1" "lb-01"
	display_funct "web-01.$1" "web-01"
	display_funct "web-02.$1" "web-02"
fi
