#!/usr/bin/env bash
# script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi 
file_name="$1"
ip_sever="$2"
user_name="$3"
path_key="$4"
scp_cmd="scp -o StrictHostKeyChecking=no -i $path_key $file_name $user_name@$ip_sever:~/"

eval $scp_cmd
