#!/usr/bin/env bash
# 
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null


echo "server {
    listen 80;
    server_name _;
    location / {
        root /var/www/html;
        index index.html;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
