#!/usr/bin/env bash 
# Configure Nginx server so that /redirect_me redirects to another page

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

echo "server {
     listen 80;
     server_name _;
     location /redirect_me {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
     }
}" > /etc/nginx/sites-available/default

sudo service nginx start
