#!/usr/bin/env bash 
# Configure Nginx server so that /redirect_me redirects to another page

echo "server {
     listen 80;
     server_name _;
     locztion /redirect_me {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
     }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
