#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
echo "server {
     listen 80;
     server_name _;
     locztion /redirect_me {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
     }

     error_page 404 /404.html;
     location = /404.html {
         root /usr/share/nginx/html;
	 internal;
	 return 404 '<html>
	              <head>
		         <title>404 Not Found</title>
		      </head>
		      <body>
		         <p>Ceci n\'est pas une page.</p>
	              </body>
		     </html>';
	     }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
