#!/usr/bin/env bash 
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

hostname=$(hostname)

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                add_header X-Served-By $hostname;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}" | sudo tee /etc/nginx/sites-available/custom_header

sudo rm -f /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
