#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 server

sudo apt-get update
sudo apt-get -y install haproxy

echo "global
	log /dev/log local0
	log /dev/log local1 notice
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000

frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back

backend http_back
	balance roundrobin
	server 340154-web-01 100.26.221.219:80 check
	server 340154-web-02 100.25.20.74:80 check" > /etc/haproxy/haproxy.cfg

if sudo service haproxy status | grep -q "not running"; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
