#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#+ also print I am invincible!!! when detect sigterm

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
