#!/usr/bin/env bash
# loops from 1 to 10 and prints bad luck, good luck and Best School

n=1
while [ $n -le 10 ]
do
        if [ $n == 4 ]; then
                echo "bad luck"
        elif [ $n == 8 ]; then
                echo "good luck"
	else
		echo "Best School"
        fi
        ((n++))
done
